spring:
  datasource:
    url: jdbc:mysql://pyokemon-account-mysql:3306/pyokemon_account?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  data:
    redis:
      host: pyokemon-redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0