server:
  port: 8082
  servlet:
    context-path: /user

spring:
  profiles:
    include:
      - flyway
      - common
  
  datasource:
    url: jdbc:mysql://localhost:3306/pyokemon_user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pyokemon
    password: pyokemon123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  flyway:
    locations: classpath:db/migration/user

# JWT 설정
jwt:
  secret-key: pyokemon-user-jwt-secret-key-2024-very-long-secret-key-for-security
  expires-in: 1800
  mobile-expires-in: 1800
  tablet-expires-in: 1800

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pyokemon.user.api.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30



