spring:
  datasource:
    url: jdbc:mysql://pyokemon-notification-mysql:3312/pyokemon_notification?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  kafka:
    bootstrap-servers: pyokemon-kafka:29092

account:
  service:
    base-url: http://pyokemon-account-service:8080/account

firebase:
  storage:
    bucket: pyokemon-8a667.appspot.com