server:
  port: 8081
  servlet:
    context-path: /event

spring:
  profiles:
    include:
      - flyway
      - common
  
  datasource:
    url: jdbc:mysql://localhost:3308/pyokemon_event?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pyokemon_event
    password: pyokemon123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    locations: classpath:db/migration/event

mybatis:
  mapper-locations: classpath:mapper/*.xml

