services:
  account-mysql:
    image: mysql:8.0
    container_name: pyokemon-account-mysql
    environment:
      MYSQL_DATABASE: pyokemon_account
      MYSQL_USER: pyokemon
      MYSQL_PASSWORD: pyokemon123
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3305:3306"
    volumes:
      - account_mysql_data:/var/lib/mysql

  event-mysql:
    image: mysql:8.0
    container_name: pyokemon-event-mysql
    environment:
      MYSQL_DATABASE: pyokemon_event
      MYSQL_USER: pyokemon_event
      MYSQL_PASSWORD: pyokemon123
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - event_mysql_data:/var/lib/mysql

  did-mysql:
    image: mysql:8.0
    container_name: pyokemon-did-mysql
    environment:
      MYSQL_DATABASE: pyokemon_did
      MYSQL_USER: pyokemon
      MYSQL_PASSWORD: pyokemon123
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - did_mysql_data:/var/lib/mysql

  payment-mysql:
    image: mysql:8.0
    container_name: pyokemon-payment-mysql
    environment:
      MYSQL_DATABASE: pyokemon_payment
      MYSQL_USER: pyokemon
      MYSQL_PASSWORD: pyokemon123
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3308:3306"
    volumes:
      - payment_mysql_data:/var/lib/mysql

  booking-mysql:
    image: mysql:8.0
    container_name: pyokemon-booking-mysql
    environment:
      MYSQL_DATABASE: pyokemon_booking
      MYSQL_USER: pyokemon
      MYSQL_PASSWORD: pyokemon123
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3311:3306"
    volumes:
      - booking_mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: pyokemon-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: pyokemon-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: pyokemon-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  account_mysql_data:
    driver: local
  event_mysql_data:
    driver: local
  payment_mysql_data:
    driver: local
  booking_mysql_data:
    driver: local
  did_mysql_data:
    driver: local
  redis_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_logs:
    driver: local
  kafka_data:
    driver: local 
