version: '3.8'

services:
  user-mysql:
    image: mysql:8.0
    container_name: pyokemon-user-mysql
    environment:
      MYSQL_DATABASE: pyokemon_user
      MYSQL_USER: pyokemon
      MYSQL_PASSWORD: pyokemon123
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - user_mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: pyokemon-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: pyokemon-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: pyokemon-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
      
  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: pyokemon-ganache
    restart: unless-stopped
    ports:
      - "8545:8545"
    command:
      - "--deterministic"
      - "--mnemonic=pyokemon blockchain did service test mnemonic words please do not use in production"
      - "--gasLimit=10000000"
      - "--accounts=10"
      - "--defaultBalanceEther=1000"
      - "--blockTime=2"
    volumes:
      - ganache_data:/ganache_data

volumes:
  user_mysql_data:
    driver: local
  redis_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_logs:
    driver: local
  kafka_data:
    driver: local
  ganache_data:
    driver: local 