def dockerImage

pipeline {
    // 특정 컨테이너를 지정하는 대신, 사용 가능한 모든 에이전트를 사용
    agent any

    // 전역 도구 설정을 파이프라인에 적용
    tools {
        gradle 'Gradle 8.5'
        jdk 'OpenJDK 21'
        dockerTool 'Docker'
    }


    environment {
        AWS_REGION     = "ap-northeast-2"
        ECR_REPO_NAME  = "pyokemon/account"
    }

    stages {
        stage('Build and Push to ECR') {
            steps {
                // Jenkins Credentials에 저장된 AWS 계정 ID를 환경 변수로 로드합니다.
                withCredentials([string(credentialsId: 'aws-account-id', variable: 'AWS_ACCOUNT_ID')]) {
                    script {
                        echo "Running Gradle build..."
                         sh "./gradlew :account:clean :account:bootJar"

                        echo "Checking for built JAR file..."
                        // 2. 빌드가 완료된 후, 생성된 파일을 확인합니다.
                        sh "ls -l account/build"
                        sh "ls -l account/build/libs"



                        // ECR 리포지토리의 전체 URL을 구성합니다.
                        def ecrRepoUrl = "${AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com"
                        // 빌드 번호를 태그로 사용해 이미지 이름을 정의합니다.
                        def imageNameWithTag = "${ecrRepoUrl}/${env.ECR_REPO_NAME}:${env.BUILD_NUMBER}"

                        echo "Building Docker image: ${imageNameWithTag}"

                        // Dockerfile을 이용해 이미지를 빌드합니다.
                        // 이제 'docker' 명령어를 바로 사용할 수 있습니다.
                        dockerImage = docker.build(imageNameWithTag, "./account/")

                        echo "Pushing image to ECR..."

                        // IAM Role을 사용하여 ECR에 로그인하고, 빌드한 이미지를 푸시합니다.
                        // 'docker' 명령어가 전역 설정에서 온 것을 인식합니다.
                        docker.withRegistry("https://${ecrRepoUrl}") {
                            dockerImage.push()
                        }
                        echo "Push successful."
                    }
                }
            }
        }
    }

    // 빌드가 성공하든 실패하든 관계없이 빌드가 끝나면 로컬에 남은 이미지를 삭제합니다.
    post {
        always {
            script {
                if (dockerImage != null) {
                    sh "docker rmi ${dockerImage.id}"
                }
            }
        }
    }
}