CREATE TABLE tb_account (
    account_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    role ENUM('USER', 'TENANT', 'ADMIN') NOT NULL,
    login_id VARCHAR(255) NOT NULL,
    password TEXT NOT NULL,
    status ENUM('ACTIVE', 'DELETED') DEFAULT 'ACTIVE',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 