spring:
  profiles:
    include:
      - flyway
      - common

  datasource:
    url: jdbc:mysql://localhost:3311/pyokemon_admin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pyokemon
    password: pyokemon123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    locations: classpath:db/migration/admin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pyokemon.admin.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

service:
  event:
    url: http://localhost:8082  # 개발 환경에서의 이벤트 서비스 URL

server:
  port: 8081

# JWT 설정
jwt:
  secret-key: "pyokemon-admin-jwt-secret-key-2024-very-long-and-secure-key-for-production"
  access-token-validity-in-minutes: 30
  refresh-token-validity-in-days: 7