server:
  port: 8082
  servlet:
    context-path: /payment

spring:
  profiles:
    include:
      - flyway
      - common
  
  datasource:
    url: jdbc:mysql://localhost:3308/pyokemon_payment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pyokemon
    password: pyokemon123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  flyway:
    locations: classpath:db/migration/payment

mybatis:
  mapper-locations: classpath:mapper/*.xml

kafka:
  listener:
    ack-mode: manual_immediate
  consumer:
    group-id: ${spring.application.name}
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    enable-auto-commit: false
    auto-offset-reset: latest
    max-poll-records: 10
    properties:
      spring.json.trusted.packages: "*"
      spring.json.use.type.headers: false  # 헤더의 타입 정보 무시
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false  # 타입

toss:
  toss-secret-key: {  }

