server:
  port: 8082
  servlet:
    context-path: /payment

spring:
  profiles:
    include:
      - flyway
      - common
  
  datasource:
    url: jdbc:mysql://localhost:3308/pyokemon_payment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pyokemon
    password: pyokemon123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  flyway:
    locations: classpath:db/migration/payment

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 10
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false  # 타입

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pyokemon.payment.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

toss:
  toss-secret-key: 


---
spring:
  config:
    activate:
      on-profile: "dev"
    import:
      - classpath:dev-config.yml