server:
  port: 8088
  servlet:
    context-path: /booking

spring:
  profiles:
    include:
      - flyway
      - common
  
  datasource:
    url: jdbc:mysql://localhost:3311/pyokemon_booking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pyokemon
    password: pyokemon123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  flyway:
    locations: classpath:db/migration/booking

mybatis:
  mapper-locations: classpath:mapper/*.xml

---
spring:
  config:
    activate:
      on-profile: "dev"
    import:
      - classpath:dev-config.yml
