spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    placeholder-replacement: true
    placeholders:
      schema: pyokemon
    validate-on-migrate: true
    out-of-order: false
    table: flyway_schema_history
    encoding: UTF-8
    create-schemas: true
    
  # Kafka 공통 설정
  kafka:
#    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual-immediate
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
      max-poll-records: 10
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

logging:
  level:
    com.pyokemon: DEBUG
    org.springframework.jdbc: DEBUG
  config: classpath:log4j2-local.yml

mybatis:
  type-aliases-package: com.pyokemon.common.entity, com.pyokemon.event.entity, com.pyokemon.event.dto, com.pyokemon.booking.entity, com.pyokemon.payment.entity, com.pyokemon.payment.dto
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

# Springdoc OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alphaZ
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:pyokemon-redis}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  kafka:
    bootstrap-servers: pyokemon-kafka:9092

# dev 환경에서 로그 환경 변수 설정
logging:
  level:
    com.pyokemon: DEBUG
  config: classpath:log4j2.yml