server:
  port: 8084
  servlet:
    context-path: /did

spring:
  profiles:
    include:
      - common
  
  datasource:
    url: jdbc:mysql://localhost:3306/pyokemon_did?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pyokemon
    password: pyokemon123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  flyway:
    locations: classpath:db/migration/did

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# ACA-Py 설정
acapy:
  tenant:
    base-url: http://localhost:8002  # pyokemon-booking-ACA-Py
    api-key: secure-key  # Docker 환경변수 ADMIN_API_KEY와 동일
    wallet-id: tenant-wallet
  mediator:
    base-url: http://localhost:8001  # pyokemon-mediator-ACA-Py (admin port)
    api-key: secure-key  # Docker 환경변수 ADMIN_API_KEY와 동일
    wallet-id: mediator-wallet
  wallet:
    key: MySecretKey123  # Wallet 생성용 키
  webhook:
    base-url: http://localhost:8084/did/webhooks
    topic-prefix: /topic/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pyokemon.did.entity 