DROP TABLE IF EXISTS tb_seat;
CREATE TABLE tb_seat (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    venue_id BIGINT NOT NULL,
    seat_class_id BIGINT NOT NULL,
    floor BIGINT NOT NULL,
    `row` VARCHAR(10) NOT NULL,
    col VARCHAR(10) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
