name: Event Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'event/**'
      - 'common/**'
      - '.github/workflows/event-service-cicd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'event/**'
      - 'common/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :event:bootJar

      - name: Deploy to Synology NAS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.NAS_SSH_PORT }}
          source: "event/build/libs/*.jar"
          target: "/volume1/docker/pyokemon/event"
          strip_components: 3

      - name: Restart service on Synology NAS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.NAS_SSH_PORT }}
          script: |
            cd /volume1/docker/pyokemon
            mv /volume1/docker/pyokemon/event/*.jar /volume1/docker/pyokemon/event/app.jar
            docker stop event-service || true
            docker rm event-service || true
            docker run -d --name event-service \
              --restart unless-stopped \
              -p 8081:8081 \
              -v /volume1/docker/pyokemon/event/app.jar:/app/app.jar \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://event-mysql:3306/pyokemon_event \
              -e SPRING_DATASOURCE_USERNAME=pyokemon_event \
              -e SPRING_DATASOURCE_PASSWORD=pyokemon123 \
              -e SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092 \
              --memory=512m \
              --memory-reservation=256m \
              --network pyokemon_network \
              eclipse-temurin:21-jre-alpine \
              java -Xms256m -Xmx512m -jar /app/app.jar 