name: Account Service CI/CD

on:
  push:
    branches: [ develop ]
    paths:
      - 'payment/**'
      - 'common/**'
      - '.github/workflows/payment-service-cicd.yml'
  pull_request:
    branches: [ develop ]
    paths:
      - 'payment/**'
      - 'common/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Build with Gradle
        run: |
          # Gradle 버전 확인
          gradle --version
          # installGitHooks 태스크 제외하고 빌드
          gradle build -x test -x installGitHooks

      - name: Deploy to Synology NAS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          port: ${{ secrets.NAS_SSH_PORT }}
          key: ${{ secrets.NAS_SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "/volume1/docker/pyokemon/payment-service"
          strip_components: 2

      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          port: ${{ secrets.NAS_SSH_PORT }}
          key: ${{ secrets.NAS_SSH_PRIVATE_KEY }}
          script: |
            cd /volume1/docker/pyokemon/payment-service
            
            # 이전 프로세스 종료
            if [ -f "app.pid" ]; then
              echo "이전 PID 파일 발견"
              PID=$(cat app.pid)
              if ps -p $PID > /dev/null 2>&1; then
                echo "프로세스 $PID 종료 시도"
                kill $PID && echo "프로세스 종료 성공" || echo "프로세스 종료 실패"
                sleep 5
              else
                echo "프로세스가 이미 종료됨"
              fi
              rm -f app.pid
            else
              echo "PID 파일 없음, 계속 진행"
            fi
            
            # 애플리케이션 실행 및 PID 저장
            echo "애플리케이션 시작"
            # Java 경로 확인
            JAVA_PATH=$(which java || echo "/usr/local/java/jdk-21.0.5+11/bin/java")
            echo "사용할 Java 경로: $JAVA_PATH"
            
            # 환경 변수 설정
            export PATH=$PATH:/usr/bin:/usr/local/java/jdk-21.0.5+11/bin/java
            export JAVA_HOME=$(dirname $(dirname $JAVA_PATH))
            
            # 애플리케이션 실행!!
            nohup $JAVA_PATH -jar payment-0.0.1.jar > app.log 2>&1 &
            echo $! > app.pid
            echo "배포 완료 (PID: $(cat app.pid))"
